[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nba-analytics"
version = "0.1.0"
description = "NBA analytics CLI"
authors = [{ name = "Mohamadou" }]
dependencies = ["pandas"]

[project.scripts]
nba-cli = "scripts.run_cli:main"

[tool.setuptools.packages.find]
where = ["."]